# Generated by Django 6.0.2 on 2026-02-07 23:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Correo electrónico único del usuario.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=True, help_text='Indica si el usuario ha verificado su correo electrónico.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUDO', 'Super User Ops'), ('ADMIN', 'Administrador'), ('USER', 'Usuario Regular')], default='USER', help_text='Rol de acceso del usuario (SUDO, ADMIN, USER).', max_length=10),
        ),
    ]
