# Generated by Django 6.0.2 on 2026-02-08 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Contenido o descripción del nodo.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha y hora de modificación (UTC).')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el nodo ha sido borrado lógicamente.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora del borrado lógico.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó este nodo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Nodo padre. Null si es un nodo raíz.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('parent__isnull', False)), fields=('content', 'parent'), name='unique_content_per_parent'), models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('parent__isnull', True)), fields=('content',), name='unique_content_for_roots')],
            },
        ),
    ]
