# Generated by Django 6.0.2 on 2026-02-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('title', 'parent'), name='unique_title_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('title',), name='unique_title_for_roots'),
        ),
    ]
