# Generated by Django 6.0.2 on 2026-02-09 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='node',
            name='unique_content_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='node',
            name='unique_content_for_roots',
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('content', 'parent'), name='unique_content_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('content',), name='unique_content_for_roots'),
        ),
    ]
