# Generated by Django 6.0.2 on 2026-02-08 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nodo', 'verbose_name_plural': 'Nodos'},
        ),
        migrations.RemoveConstraint(
            model_name='node',
            name='unique_title_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='node',
            name='unique_title_for_roots',
        ),
        migrations.AddField(
            model_name='node',
            name='content',
            field=models.CharField(default=None, help_text='Contenido o descripción del nodo.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (UTC).'),
        ),
        migrations.AlterField(
            model_name='node',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del borrado lógico.', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si el nodo ha sido borrado lógicamente.'),
        ),
        migrations.AlterField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Nodo padre. Null si es un nodo raíz.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='nodes.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última fecha y hora de modificación (UTC).'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('parent__isnull', False)), fields=('content', 'parent'), name='unique_content_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('parent__isnull', True)), fields=('content',), name='unique_content_for_roots'),
        ),
        migrations.RemoveField(
            model_name='node',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='node',
            name='title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='updated_by',
        ),
    ]
